version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=false
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ACCESS_KEY=${ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - ENV=${ENV}
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile_Db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data




volumes:
  postgres-data:
  static-data:
