# Generated by Django 4.0.10 on 2025-07-09 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_title', models.CharField(max_length=255)),
                ('ad_format', models.CharField(max_length=50)),
                ('product_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advertiser_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeHierarchy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_key', models.DateField(primary_key=True, serialize=False)),
                ('hour', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('weekday_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Time hierarchies',
            },
        ),
        migrations.CreateModel(
            name='SpendSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('gross_spend', models.FloatField()),
                ('net_spend', models.FloatField()),
                ('budget_at_time', models.FloatField()),
                ('can_serve', models.BooleanField(default=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertiser')),
            ],
            options={
                'verbose_name_plural': 'Spend summaries',
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('click_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('is_valid', models.BooleanField(default=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ad')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertiser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('new_budget_value', models.FloatField()),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=50)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertiser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertiser'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.advertiser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
