# Generated by Django 5.0.2 on 2024-05-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='click_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.IntegerField()),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_click_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='click_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.IntegerField()),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_click_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='click_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.IntegerField()),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_click_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='click_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.IntegerField()),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_click_4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='conversions_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.IntegerField()),
                ('click_id', models.IntegerField()),
                ('revenue', models.TextField()),
            ],
            options={
                'db_table': 'core_conversions_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='conversions_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.IntegerField()),
                ('click_id', models.IntegerField()),
                ('revenue', models.TextField()),
            ],
            options={
                'db_table': 'core_conversions_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='conversions_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.IntegerField()),
                ('click_id', models.IntegerField()),
                ('revenue', models.TextField()),
            ],
            options={
                'db_table': 'core_conversions_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='conversions_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.IntegerField()),
                ('click_id', models.IntegerField()),
                ('revenue', models.TextField()),
            ],
            options={
                'db_table': 'core_conversions_4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='impressions_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_impressions_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='impressions_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_impressions_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='impressions_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_impressions_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='impressions_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_impressions_4',
                'managed': False,
            },
        ),
    ]
